layout {

  page {
    height = 9840
    bottom-padding = 100
    width = 524
  }

  styles {
    1 {
      pt = 11
      line-height = 162
      font-name = times // times or courier
      font-weight = BOLD // BOLD
    }

    2 {
      pt = 12
      line-height = 177
      font-name = times // times or courier
      font-weight = BOLD // BOLD
    }

    3 {
      pt = 16
      line-height = 236
      font-name = times // times or courier
      font-weight = BOLD // BOLD
    }

    4 {
      pt = 9
      line-height = 131
      font-name = courier // times or courier
      font-weight = PLAIN // PLAIN
    }

    5 {
      pt = 10
      line-height = 153
      font-name = courier // times or courier
      font-weight = PLAIN // PLAIN
    }

    6 {
      pt = 8
      line-height = 115
      font-name = courier // times or courier
      font-weight = PLAIN // PLAIN
    }

  }

}

ranking {
  start-limit: 10
  finish-limit: 6
  sum-count: 10
}
